preload = /home/ian/.config/hypr/wallpapers/2077/main.png
preload = /home/ian/.config/hypr/wallpapers/2077/mainVert.png

wallpaper {
    monitor = HDMI-A-2
    path = /home/ian/.config/hypr/wallpapers/2077/main.png
}

wallpaper {
    monitor = DP-2
    path = /home/ian/.config/hypr/wallpapers/2077/mainVert.png
}


# ...
